//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogControl.ApiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Post", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Post : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        private System.DateTime CreatedAtField;
        
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlogControl.ApiService.Category CategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AuthorID {
            get {
                return this.AuthorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorIDField, value) != true)) {
                    this.AuthorIDField = value;
                    this.RaisePropertyChanged("AuthorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Caption {
            get {
                return this.CaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CaptionField, value) != true)) {
                    this.CaptionField = value;
                    this.RaisePropertyChanged("Caption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BlogControl.ApiService.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserEx", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserEx : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        private bool IsAdministratorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool IsAdministrator {
            get {
                return this.IsAdministratorField;
            }
            set {
                if ((this.IsAdministratorField.Equals(value) != true)) {
                    this.IsAdministratorField = value;
                    this.RaisePropertyChanged("IsAdministrator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentEx", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CommentEx : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorNameField;
        
        private System.DateTime CreatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AuthorName {
            get {
                return this.AuthorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorNameField, value) != true)) {
                    this.AuthorNameField = value;
                    this.RaisePropertyChanged("AuthorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PostName {
            get {
                return this.PostNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PostNameField, value) != true)) {
                    this.PostNameField = value;
                    this.RaisePropertyChanged("PostName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApiService.ApiSoap")]
    public interface ApiSoap {
        
        // CODEGEN: Generating message contract since element name GetPostsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosts", ReplyAction="*")]
        BlogControl.ApiService.GetPostsResponse GetPosts(BlogControl.ApiService.GetPostsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosts", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetPostsResponse> GetPostsAsync(BlogControl.ApiService.GetPostsRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        BlogControl.ApiService.LoginResponse Login(BlogControl.ApiService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.LoginResponse> LoginAsync(BlogControl.ApiService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        BlogControl.ApiService.GetUserResponse GetUser(BlogControl.ApiService.GetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetUserResponse> GetUserAsync(BlogControl.ApiService.GetUserRequest request);
        
        // CODEGEN: Generating message contract since element name GetUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        BlogControl.ApiService.GetUsersResponse GetUsers(BlogControl.ApiService.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetUsersResponse> GetUsersAsync(BlogControl.ApiService.GetUsersRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        BlogControl.ApiService.DeleteUserResponse DeleteUser(BlogControl.ApiService.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.DeleteUserResponse> DeleteUserAsync(BlogControl.ApiService.DeleteUserRequest request);
        
        // CODEGEN: Generating message contract since element name ex from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        BlogControl.ApiService.AddUserResponse AddUser(BlogControl.ApiService.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.AddUserResponse> AddUserAsync(BlogControl.ApiService.AddUserRequest request);
        
        // CODEGEN: Generating message contract since element name ex from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        BlogControl.ApiService.UpdateUserResponse UpdateUser(BlogControl.ApiService.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.UpdateUserResponse> UpdateUserAsync(BlogControl.ApiService.UpdateUserRequest request);
        
        // CODEGEN: Generating message contract since element name GetCategoriesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategories", ReplyAction="*")]
        BlogControl.ApiService.GetCategoriesResponse GetCategories(BlogControl.ApiService.GetCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetCategoriesResponse> GetCategoriesAsync(BlogControl.ApiService.GetCategoriesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCategoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategory", ReplyAction="*")]
        BlogControl.ApiService.GetCategoryResponse GetCategory(BlogControl.ApiService.GetCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetCategoryResponse> GetCategoryAsync(BlogControl.ApiService.GetCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCategory", ReplyAction="*")]
        bool DeleteCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCategoryAsync(int id);
        
        // CODEGEN: Generating message contract since element name category from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCategory", ReplyAction="*")]
        BlogControl.ApiService.AddCategoryResponse AddCategory(BlogControl.ApiService.AddCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.AddCategoryResponse> AddCategoryAsync(BlogControl.ApiService.AddCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name category from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCategory", ReplyAction="*")]
        BlogControl.ApiService.UpdateCategoryResponse UpdateCategory(BlogControl.ApiService.UpdateCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.UpdateCategoryResponse> UpdateCategoryAsync(BlogControl.ApiService.UpdateCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name GetCommentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetComments", ReplyAction="*")]
        BlogControl.ApiService.GetCommentsResponse GetComments(BlogControl.ApiService.GetCommentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetComments", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetCommentsResponse> GetCommentsAsync(BlogControl.ApiService.GetCommentsRequest request);
        
        // CODEGEN: Generating message contract since element name GetCommentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetComment", ReplyAction="*")]
        BlogControl.ApiService.GetCommentResponse GetComment(BlogControl.ApiService.GetCommentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetComment", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetCommentResponse> GetCommentAsync(BlogControl.ApiService.GetCommentRequest request);
        
        // CODEGEN: Generating message contract since element name comment from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateComment", ReplyAction="*")]
        BlogControl.ApiService.UpdateCommentResponse UpdateComment(BlogControl.ApiService.UpdateCommentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateComment", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.UpdateCommentResponse> UpdateCommentAsync(BlogControl.ApiService.UpdateCommentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteComment", ReplyAction="*")]
        bool DeleteComment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteComment", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCommentAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosts", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetPostsRequestBody Body;
        
        public GetPostsRequest() {
        }
        
        public GetPostsRequest(BlogControl.ApiService.GetPostsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPostsRequestBody {
        
        public GetPostsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetPostsResponseBody Body;
        
        public GetPostsResponse() {
        }
        
        public GetPostsResponse(BlogControl.ApiService.GetPostsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPostsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.Post[] GetPostsResult;
        
        public GetPostsResponseBody() {
        }
        
        public GetPostsResponseBody(BlogControl.ApiService.Post[] GetPostsResult) {
            this.GetPostsResult = GetPostsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(BlogControl.ApiService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(BlogControl.ApiService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUser", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetUserRequestBody Body;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(BlogControl.ApiService.GetUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public GetUserRequestBody() {
        }
        
        public GetUserRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetUserResponseBody Body;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(BlogControl.ApiService.GetUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.UserEx GetUserResult;
        
        public GetUserResponseBody() {
        }
        
        public GetUserResponseBody(BlogControl.ApiService.UserEx GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(BlogControl.ApiService.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsersRequestBody {
        
        public GetUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(BlogControl.ApiService.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.UserEx[] GetUsersResult;
        
        public GetUsersResponseBody() {
        }
        
        public GetUsersResponseBody(BlogControl.ApiService.UserEx[] GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUser", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.DeleteUserRequestBody Body;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(BlogControl.ApiService.DeleteUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public DeleteUserRequestBody() {
        }
        
        public DeleteUserRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.DeleteUserResponseBody Body;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(BlogControl.ApiService.DeleteUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteUserResult;
        
        public DeleteUserResponseBody() {
        }
        
        public DeleteUserResponseBody(bool DeleteUserResult) {
            this.DeleteUserResult = DeleteUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(BlogControl.ApiService.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.UserEx ex;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(BlogControl.ApiService.UserEx ex) {
            this.ex = ex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(BlogControl.ApiService.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddUserResult;
        
        public AddUserResponseBody() {
        }
        
        public AddUserResponseBody(bool AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUser", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.UpdateUserRequestBody Body;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(BlogControl.ApiService.UpdateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.UserEx ex;
        
        public UpdateUserRequestBody() {
        }
        
        public UpdateUserRequestBody(BlogControl.ApiService.UserEx ex) {
            this.ex = ex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.UpdateUserResponseBody Body;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(BlogControl.ApiService.UpdateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUserResult;
        
        public UpdateUserResponseBody() {
        }
        
        public UpdateUserResponseBody(bool UpdateUserResult) {
            this.UpdateUserResult = UpdateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategories", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetCategoriesRequestBody Body;
        
        public GetCategoriesRequest() {
        }
        
        public GetCategoriesRequest(BlogControl.ApiService.GetCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCategoriesRequestBody {
        
        public GetCategoriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetCategoriesResponseBody Body;
        
        public GetCategoriesResponse() {
        }
        
        public GetCategoriesResponse(BlogControl.ApiService.GetCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.Category[] GetCategoriesResult;
        
        public GetCategoriesResponseBody() {
        }
        
        public GetCategoriesResponseBody(BlogControl.ApiService.Category[] GetCategoriesResult) {
            this.GetCategoriesResult = GetCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategory", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetCategoryRequestBody Body;
        
        public GetCategoryRequest() {
        }
        
        public GetCategoryRequest(BlogControl.ApiService.GetCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCategoryRequestBody() {
        }
        
        public GetCategoryRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetCategoryResponseBody Body;
        
        public GetCategoryResponse() {
        }
        
        public GetCategoryResponse(BlogControl.ApiService.GetCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.Category GetCategoryResult;
        
        public GetCategoryResponseBody() {
        }
        
        public GetCategoryResponseBody(BlogControl.ApiService.Category GetCategoryResult) {
            this.GetCategoryResult = GetCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCategory", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.AddCategoryRequestBody Body;
        
        public AddCategoryRequest() {
        }
        
        public AddCategoryRequest(BlogControl.ApiService.AddCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.Category category;
        
        public AddCategoryRequestBody() {
        }
        
        public AddCategoryRequestBody(BlogControl.ApiService.Category category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.AddCategoryResponseBody Body;
        
        public AddCategoryResponse() {
        }
        
        public AddCategoryResponse(BlogControl.ApiService.AddCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddCategoryResult;
        
        public AddCategoryResponseBody() {
        }
        
        public AddCategoryResponseBody(bool AddCategoryResult) {
            this.AddCategoryResult = AddCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCategory", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.UpdateCategoryRequestBody Body;
        
        public UpdateCategoryRequest() {
        }
        
        public UpdateCategoryRequest(BlogControl.ApiService.UpdateCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.Category category;
        
        public UpdateCategoryRequestBody() {
        }
        
        public UpdateCategoryRequestBody(BlogControl.ApiService.Category category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.UpdateCategoryResponseBody Body;
        
        public UpdateCategoryResponse() {
        }
        
        public UpdateCategoryResponse(BlogControl.ApiService.UpdateCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateCategoryResult;
        
        public UpdateCategoryResponseBody() {
        }
        
        public UpdateCategoryResponseBody(bool UpdateCategoryResult) {
            this.UpdateCategoryResult = UpdateCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComments", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetCommentsRequestBody Body;
        
        public GetCommentsRequest() {
        }
        
        public GetCommentsRequest(BlogControl.ApiService.GetCommentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCommentsRequestBody {
        
        public GetCommentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetCommentsResponseBody Body;
        
        public GetCommentsResponse() {
        }
        
        public GetCommentsResponse(BlogControl.ApiService.GetCommentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.CommentEx[] GetCommentsResult;
        
        public GetCommentsResponseBody() {
        }
        
        public GetCommentsResponseBody(BlogControl.ApiService.CommentEx[] GetCommentsResult) {
            this.GetCommentsResult = GetCommentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComment", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetCommentRequestBody Body;
        
        public GetCommentRequest() {
        }
        
        public GetCommentRequest(BlogControl.ApiService.GetCommentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCommentRequestBody() {
        }
        
        public GetCommentRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCommentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCommentResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetCommentResponseBody Body;
        
        public GetCommentResponse() {
        }
        
        public GetCommentResponse(BlogControl.ApiService.GetCommentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCommentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.CommentEx GetCommentResult;
        
        public GetCommentResponseBody() {
        }
        
        public GetCommentResponseBody(BlogControl.ApiService.CommentEx GetCommentResult) {
            this.GetCommentResult = GetCommentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCommentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateComment", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.UpdateCommentRequestBody Body;
        
        public UpdateCommentRequest() {
        }
        
        public UpdateCommentRequest(BlogControl.ApiService.UpdateCommentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCommentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.CommentEx comment;
        
        public UpdateCommentRequestBody() {
        }
        
        public UpdateCommentRequestBody(BlogControl.ApiService.CommentEx comment) {
            this.comment = comment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCommentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCommentResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.UpdateCommentResponseBody Body;
        
        public UpdateCommentResponse() {
        }
        
        public UpdateCommentResponse(BlogControl.ApiService.UpdateCommentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCommentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateCommentResult;
        
        public UpdateCommentResponseBody() {
        }
        
        public UpdateCommentResponseBody(bool UpdateCommentResult) {
            this.UpdateCommentResult = UpdateCommentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiSoapChannel : BlogControl.ApiService.ApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiSoapClient : System.ServiceModel.ClientBase<BlogControl.ApiService.ApiSoap>, BlogControl.ApiService.ApiSoap {
        
        public ApiSoapClient() {
        }
        
        public ApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.GetPostsResponse BlogControl.ApiService.ApiSoap.GetPosts(BlogControl.ApiService.GetPostsRequest request) {
            return base.Channel.GetPosts(request);
        }
        
        public BlogControl.ApiService.Post[] GetPosts() {
            BlogControl.ApiService.GetPostsRequest inValue = new BlogControl.ApiService.GetPostsRequest();
            inValue.Body = new BlogControl.ApiService.GetPostsRequestBody();
            BlogControl.ApiService.GetPostsResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).GetPosts(inValue);
            return retVal.Body.GetPostsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetPostsResponse> BlogControl.ApiService.ApiSoap.GetPostsAsync(BlogControl.ApiService.GetPostsRequest request) {
            return base.Channel.GetPostsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.GetPostsResponse> GetPostsAsync() {
            BlogControl.ApiService.GetPostsRequest inValue = new BlogControl.ApiService.GetPostsRequest();
            inValue.Body = new BlogControl.ApiService.GetPostsRequestBody();
            return ((BlogControl.ApiService.ApiSoap)(this)).GetPostsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.LoginResponse BlogControl.ApiService.ApiSoap.Login(BlogControl.ApiService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string email, string password) {
            BlogControl.ApiService.LoginRequest inValue = new BlogControl.ApiService.LoginRequest();
            inValue.Body = new BlogControl.ApiService.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            BlogControl.ApiService.LoginResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.LoginResponse> BlogControl.ApiService.ApiSoap.LoginAsync(BlogControl.ApiService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.LoginResponse> LoginAsync(string email, string password) {
            BlogControl.ApiService.LoginRequest inValue = new BlogControl.ApiService.LoginRequest();
            inValue.Body = new BlogControl.ApiService.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((BlogControl.ApiService.ApiSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.GetUserResponse BlogControl.ApiService.ApiSoap.GetUser(BlogControl.ApiService.GetUserRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public BlogControl.ApiService.UserEx GetUser(string email) {
            BlogControl.ApiService.GetUserRequest inValue = new BlogControl.ApiService.GetUserRequest();
            inValue.Body = new BlogControl.ApiService.GetUserRequestBody();
            inValue.Body.email = email;
            BlogControl.ApiService.GetUserResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).GetUser(inValue);
            return retVal.Body.GetUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetUserResponse> BlogControl.ApiService.ApiSoap.GetUserAsync(BlogControl.ApiService.GetUserRequest request) {
            return base.Channel.GetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.GetUserResponse> GetUserAsync(string email) {
            BlogControl.ApiService.GetUserRequest inValue = new BlogControl.ApiService.GetUserRequest();
            inValue.Body = new BlogControl.ApiService.GetUserRequestBody();
            inValue.Body.email = email;
            return ((BlogControl.ApiService.ApiSoap)(this)).GetUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.GetUsersResponse BlogControl.ApiService.ApiSoap.GetUsers(BlogControl.ApiService.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public BlogControl.ApiService.UserEx[] GetUsers() {
            BlogControl.ApiService.GetUsersRequest inValue = new BlogControl.ApiService.GetUsersRequest();
            inValue.Body = new BlogControl.ApiService.GetUsersRequestBody();
            BlogControl.ApiService.GetUsersResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).GetUsers(inValue);
            return retVal.Body.GetUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetUsersResponse> BlogControl.ApiService.ApiSoap.GetUsersAsync(BlogControl.ApiService.GetUsersRequest request) {
            return base.Channel.GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.GetUsersResponse> GetUsersAsync() {
            BlogControl.ApiService.GetUsersRequest inValue = new BlogControl.ApiService.GetUsersRequest();
            inValue.Body = new BlogControl.ApiService.GetUsersRequestBody();
            return ((BlogControl.ApiService.ApiSoap)(this)).GetUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.DeleteUserResponse BlogControl.ApiService.ApiSoap.DeleteUser(BlogControl.ApiService.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public bool DeleteUser(string email) {
            BlogControl.ApiService.DeleteUserRequest inValue = new BlogControl.ApiService.DeleteUserRequest();
            inValue.Body = new BlogControl.ApiService.DeleteUserRequestBody();
            inValue.Body.email = email;
            BlogControl.ApiService.DeleteUserResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).DeleteUser(inValue);
            return retVal.Body.DeleteUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.DeleteUserResponse> BlogControl.ApiService.ApiSoap.DeleteUserAsync(BlogControl.ApiService.DeleteUserRequest request) {
            return base.Channel.DeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.DeleteUserResponse> DeleteUserAsync(string email) {
            BlogControl.ApiService.DeleteUserRequest inValue = new BlogControl.ApiService.DeleteUserRequest();
            inValue.Body = new BlogControl.ApiService.DeleteUserRequestBody();
            inValue.Body.email = email;
            return ((BlogControl.ApiService.ApiSoap)(this)).DeleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.AddUserResponse BlogControl.ApiService.ApiSoap.AddUser(BlogControl.ApiService.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public bool AddUser(BlogControl.ApiService.UserEx ex) {
            BlogControl.ApiService.AddUserRequest inValue = new BlogControl.ApiService.AddUserRequest();
            inValue.Body = new BlogControl.ApiService.AddUserRequestBody();
            inValue.Body.ex = ex;
            BlogControl.ApiService.AddUserResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.AddUserResponse> BlogControl.ApiService.ApiSoap.AddUserAsync(BlogControl.ApiService.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.AddUserResponse> AddUserAsync(BlogControl.ApiService.UserEx ex) {
            BlogControl.ApiService.AddUserRequest inValue = new BlogControl.ApiService.AddUserRequest();
            inValue.Body = new BlogControl.ApiService.AddUserRequestBody();
            inValue.Body.ex = ex;
            return ((BlogControl.ApiService.ApiSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.UpdateUserResponse BlogControl.ApiService.ApiSoap.UpdateUser(BlogControl.ApiService.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public bool UpdateUser(BlogControl.ApiService.UserEx ex) {
            BlogControl.ApiService.UpdateUserRequest inValue = new BlogControl.ApiService.UpdateUserRequest();
            inValue.Body = new BlogControl.ApiService.UpdateUserRequestBody();
            inValue.Body.ex = ex;
            BlogControl.ApiService.UpdateUserResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).UpdateUser(inValue);
            return retVal.Body.UpdateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.UpdateUserResponse> BlogControl.ApiService.ApiSoap.UpdateUserAsync(BlogControl.ApiService.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.UpdateUserResponse> UpdateUserAsync(BlogControl.ApiService.UserEx ex) {
            BlogControl.ApiService.UpdateUserRequest inValue = new BlogControl.ApiService.UpdateUserRequest();
            inValue.Body = new BlogControl.ApiService.UpdateUserRequestBody();
            inValue.Body.ex = ex;
            return ((BlogControl.ApiService.ApiSoap)(this)).UpdateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.GetCategoriesResponse BlogControl.ApiService.ApiSoap.GetCategories(BlogControl.ApiService.GetCategoriesRequest request) {
            return base.Channel.GetCategories(request);
        }
        
        public BlogControl.ApiService.Category[] GetCategories() {
            BlogControl.ApiService.GetCategoriesRequest inValue = new BlogControl.ApiService.GetCategoriesRequest();
            inValue.Body = new BlogControl.ApiService.GetCategoriesRequestBody();
            BlogControl.ApiService.GetCategoriesResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).GetCategories(inValue);
            return retVal.Body.GetCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetCategoriesResponse> BlogControl.ApiService.ApiSoap.GetCategoriesAsync(BlogControl.ApiService.GetCategoriesRequest request) {
            return base.Channel.GetCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.GetCategoriesResponse> GetCategoriesAsync() {
            BlogControl.ApiService.GetCategoriesRequest inValue = new BlogControl.ApiService.GetCategoriesRequest();
            inValue.Body = new BlogControl.ApiService.GetCategoriesRequestBody();
            return ((BlogControl.ApiService.ApiSoap)(this)).GetCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.GetCategoryResponse BlogControl.ApiService.ApiSoap.GetCategory(BlogControl.ApiService.GetCategoryRequest request) {
            return base.Channel.GetCategory(request);
        }
        
        public BlogControl.ApiService.Category GetCategory(int id) {
            BlogControl.ApiService.GetCategoryRequest inValue = new BlogControl.ApiService.GetCategoryRequest();
            inValue.Body = new BlogControl.ApiService.GetCategoryRequestBody();
            inValue.Body.id = id;
            BlogControl.ApiService.GetCategoryResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).GetCategory(inValue);
            return retVal.Body.GetCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetCategoryResponse> BlogControl.ApiService.ApiSoap.GetCategoryAsync(BlogControl.ApiService.GetCategoryRequest request) {
            return base.Channel.GetCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.GetCategoryResponse> GetCategoryAsync(int id) {
            BlogControl.ApiService.GetCategoryRequest inValue = new BlogControl.ApiService.GetCategoryRequest();
            inValue.Body = new BlogControl.ApiService.GetCategoryRequestBody();
            inValue.Body.id = id;
            return ((BlogControl.ApiService.ApiSoap)(this)).GetCategoryAsync(inValue);
        }
        
        public bool DeleteCategory(int id) {
            return base.Channel.DeleteCategory(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCategoryAsync(int id) {
            return base.Channel.DeleteCategoryAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.AddCategoryResponse BlogControl.ApiService.ApiSoap.AddCategory(BlogControl.ApiService.AddCategoryRequest request) {
            return base.Channel.AddCategory(request);
        }
        
        public bool AddCategory(BlogControl.ApiService.Category category) {
            BlogControl.ApiService.AddCategoryRequest inValue = new BlogControl.ApiService.AddCategoryRequest();
            inValue.Body = new BlogControl.ApiService.AddCategoryRequestBody();
            inValue.Body.category = category;
            BlogControl.ApiService.AddCategoryResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).AddCategory(inValue);
            return retVal.Body.AddCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.AddCategoryResponse> BlogControl.ApiService.ApiSoap.AddCategoryAsync(BlogControl.ApiService.AddCategoryRequest request) {
            return base.Channel.AddCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.AddCategoryResponse> AddCategoryAsync(BlogControl.ApiService.Category category) {
            BlogControl.ApiService.AddCategoryRequest inValue = new BlogControl.ApiService.AddCategoryRequest();
            inValue.Body = new BlogControl.ApiService.AddCategoryRequestBody();
            inValue.Body.category = category;
            return ((BlogControl.ApiService.ApiSoap)(this)).AddCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.UpdateCategoryResponse BlogControl.ApiService.ApiSoap.UpdateCategory(BlogControl.ApiService.UpdateCategoryRequest request) {
            return base.Channel.UpdateCategory(request);
        }
        
        public bool UpdateCategory(BlogControl.ApiService.Category category) {
            BlogControl.ApiService.UpdateCategoryRequest inValue = new BlogControl.ApiService.UpdateCategoryRequest();
            inValue.Body = new BlogControl.ApiService.UpdateCategoryRequestBody();
            inValue.Body.category = category;
            BlogControl.ApiService.UpdateCategoryResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).UpdateCategory(inValue);
            return retVal.Body.UpdateCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.UpdateCategoryResponse> BlogControl.ApiService.ApiSoap.UpdateCategoryAsync(BlogControl.ApiService.UpdateCategoryRequest request) {
            return base.Channel.UpdateCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.UpdateCategoryResponse> UpdateCategoryAsync(BlogControl.ApiService.Category category) {
            BlogControl.ApiService.UpdateCategoryRequest inValue = new BlogControl.ApiService.UpdateCategoryRequest();
            inValue.Body = new BlogControl.ApiService.UpdateCategoryRequestBody();
            inValue.Body.category = category;
            return ((BlogControl.ApiService.ApiSoap)(this)).UpdateCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.GetCommentsResponse BlogControl.ApiService.ApiSoap.GetComments(BlogControl.ApiService.GetCommentsRequest request) {
            return base.Channel.GetComments(request);
        }
        
        public BlogControl.ApiService.CommentEx[] GetComments() {
            BlogControl.ApiService.GetCommentsRequest inValue = new BlogControl.ApiService.GetCommentsRequest();
            inValue.Body = new BlogControl.ApiService.GetCommentsRequestBody();
            BlogControl.ApiService.GetCommentsResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).GetComments(inValue);
            return retVal.Body.GetCommentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetCommentsResponse> BlogControl.ApiService.ApiSoap.GetCommentsAsync(BlogControl.ApiService.GetCommentsRequest request) {
            return base.Channel.GetCommentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.GetCommentsResponse> GetCommentsAsync() {
            BlogControl.ApiService.GetCommentsRequest inValue = new BlogControl.ApiService.GetCommentsRequest();
            inValue.Body = new BlogControl.ApiService.GetCommentsRequestBody();
            return ((BlogControl.ApiService.ApiSoap)(this)).GetCommentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.GetCommentResponse BlogControl.ApiService.ApiSoap.GetComment(BlogControl.ApiService.GetCommentRequest request) {
            return base.Channel.GetComment(request);
        }
        
        public BlogControl.ApiService.CommentEx GetComment(int id) {
            BlogControl.ApiService.GetCommentRequest inValue = new BlogControl.ApiService.GetCommentRequest();
            inValue.Body = new BlogControl.ApiService.GetCommentRequestBody();
            inValue.Body.id = id;
            BlogControl.ApiService.GetCommentResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).GetComment(inValue);
            return retVal.Body.GetCommentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetCommentResponse> BlogControl.ApiService.ApiSoap.GetCommentAsync(BlogControl.ApiService.GetCommentRequest request) {
            return base.Channel.GetCommentAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.GetCommentResponse> GetCommentAsync(int id) {
            BlogControl.ApiService.GetCommentRequest inValue = new BlogControl.ApiService.GetCommentRequest();
            inValue.Body = new BlogControl.ApiService.GetCommentRequestBody();
            inValue.Body.id = id;
            return ((BlogControl.ApiService.ApiSoap)(this)).GetCommentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.UpdateCommentResponse BlogControl.ApiService.ApiSoap.UpdateComment(BlogControl.ApiService.UpdateCommentRequest request) {
            return base.Channel.UpdateComment(request);
        }
        
        public bool UpdateComment(BlogControl.ApiService.CommentEx comment) {
            BlogControl.ApiService.UpdateCommentRequest inValue = new BlogControl.ApiService.UpdateCommentRequest();
            inValue.Body = new BlogControl.ApiService.UpdateCommentRequestBody();
            inValue.Body.comment = comment;
            BlogControl.ApiService.UpdateCommentResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).UpdateComment(inValue);
            return retVal.Body.UpdateCommentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.UpdateCommentResponse> BlogControl.ApiService.ApiSoap.UpdateCommentAsync(BlogControl.ApiService.UpdateCommentRequest request) {
            return base.Channel.UpdateCommentAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.UpdateCommentResponse> UpdateCommentAsync(BlogControl.ApiService.CommentEx comment) {
            BlogControl.ApiService.UpdateCommentRequest inValue = new BlogControl.ApiService.UpdateCommentRequest();
            inValue.Body = new BlogControl.ApiService.UpdateCommentRequestBody();
            inValue.Body.comment = comment;
            return ((BlogControl.ApiService.ApiSoap)(this)).UpdateCommentAsync(inValue);
        }
        
        public bool DeleteComment(int id) {
            return base.Channel.DeleteComment(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCommentAsync(int id) {
            return base.Channel.DeleteCommentAsync(id);
        }
    }
}
