//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogControl.ApiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Post", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Post : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        private System.DateTime CreatedAtField;
        
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlogControl.ApiService.Category CategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AuthorID {
            get {
                return this.AuthorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorIDField, value) != true)) {
                    this.AuthorIDField = value;
                    this.RaisePropertyChanged("AuthorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Caption {
            get {
                return this.CaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CaptionField, value) != true)) {
                    this.CaptionField = value;
                    this.RaisePropertyChanged("Caption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public BlogControl.ApiService.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApiService.ApiSoap")]
    public interface ApiSoap {
        
        // CODEGEN: Generating message contract since element name GetPostsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosts", ReplyAction="*")]
        BlogControl.ApiService.GetPostsResponse GetPosts(BlogControl.ApiService.GetPostsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPosts", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetPostsResponse> GetPostsAsync(BlogControl.ApiService.GetPostsRequest request);
        
        // CODEGEN: Generating message contract since element name GetCategoriesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategories", ReplyAction="*")]
        BlogControl.ApiService.GetCategoriesResponse GetCategories(BlogControl.ApiService.GetCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetCategoriesResponse> GetCategoriesAsync(BlogControl.ApiService.GetCategoriesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCategoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategory", ReplyAction="*")]
        BlogControl.ApiService.GetCategoryResponse GetCategory(BlogControl.ApiService.GetCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetCategoryResponse> GetCategoryAsync(BlogControl.ApiService.GetCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCategory", ReplyAction="*")]
        bool DeleteCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteCategoryAsync(int id);
        
        // CODEGEN: Generating message contract since element name category from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCategory", ReplyAction="*")]
        BlogControl.ApiService.AddCategoryResponse AddCategory(BlogControl.ApiService.AddCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.AddCategoryResponse> AddCategoryAsync(BlogControl.ApiService.AddCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name category from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCategory", ReplyAction="*")]
        BlogControl.ApiService.UpdateCategoryResponse UpdateCategory(BlogControl.ApiService.UpdateCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<BlogControl.ApiService.UpdateCategoryResponse> UpdateCategoryAsync(BlogControl.ApiService.UpdateCategoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosts", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetPostsRequestBody Body;
        
        public GetPostsRequest() {
        }
        
        public GetPostsRequest(BlogControl.ApiService.GetPostsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPostsRequestBody {
        
        public GetPostsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetPostsResponseBody Body;
        
        public GetPostsResponse() {
        }
        
        public GetPostsResponse(BlogControl.ApiService.GetPostsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPostsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.Post[] GetPostsResult;
        
        public GetPostsResponseBody() {
        }
        
        public GetPostsResponseBody(BlogControl.ApiService.Post[] GetPostsResult) {
            this.GetPostsResult = GetPostsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategories", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetCategoriesRequestBody Body;
        
        public GetCategoriesRequest() {
        }
        
        public GetCategoriesRequest(BlogControl.ApiService.GetCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCategoriesRequestBody {
        
        public GetCategoriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetCategoriesResponseBody Body;
        
        public GetCategoriesResponse() {
        }
        
        public GetCategoriesResponse(BlogControl.ApiService.GetCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.Category[] GetCategoriesResult;
        
        public GetCategoriesResponseBody() {
        }
        
        public GetCategoriesResponseBody(BlogControl.ApiService.Category[] GetCategoriesResult) {
            this.GetCategoriesResult = GetCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategory", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetCategoryRequestBody Body;
        
        public GetCategoryRequest() {
        }
        
        public GetCategoryRequest(BlogControl.ApiService.GetCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCategoryRequestBody() {
        }
        
        public GetCategoryRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.GetCategoryResponseBody Body;
        
        public GetCategoryResponse() {
        }
        
        public GetCategoryResponse(BlogControl.ApiService.GetCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.Category GetCategoryResult;
        
        public GetCategoryResponseBody() {
        }
        
        public GetCategoryResponseBody(BlogControl.ApiService.Category GetCategoryResult) {
            this.GetCategoryResult = GetCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCategory", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.AddCategoryRequestBody Body;
        
        public AddCategoryRequest() {
        }
        
        public AddCategoryRequest(BlogControl.ApiService.AddCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.Category category;
        
        public AddCategoryRequestBody() {
        }
        
        public AddCategoryRequestBody(BlogControl.ApiService.Category category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.AddCategoryResponseBody Body;
        
        public AddCategoryResponse() {
        }
        
        public AddCategoryResponse(BlogControl.ApiService.AddCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddCategoryResult;
        
        public AddCategoryResponseBody() {
        }
        
        public AddCategoryResponseBody(bool AddCategoryResult) {
            this.AddCategoryResult = AddCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCategory", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.UpdateCategoryRequestBody Body;
        
        public UpdateCategoryRequest() {
        }
        
        public UpdateCategoryRequest(BlogControl.ApiService.UpdateCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BlogControl.ApiService.Category category;
        
        public UpdateCategoryRequestBody() {
        }
        
        public UpdateCategoryRequestBody(BlogControl.ApiService.Category category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public BlogControl.ApiService.UpdateCategoryResponseBody Body;
        
        public UpdateCategoryResponse() {
        }
        
        public UpdateCategoryResponse(BlogControl.ApiService.UpdateCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateCategoryResult;
        
        public UpdateCategoryResponseBody() {
        }
        
        public UpdateCategoryResponseBody(bool UpdateCategoryResult) {
            this.UpdateCategoryResult = UpdateCategoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiSoapChannel : BlogControl.ApiService.ApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiSoapClient : System.ServiceModel.ClientBase<BlogControl.ApiService.ApiSoap>, BlogControl.ApiService.ApiSoap {
        
        public ApiSoapClient() {
        }
        
        public ApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.GetPostsResponse BlogControl.ApiService.ApiSoap.GetPosts(BlogControl.ApiService.GetPostsRequest request) {
            return base.Channel.GetPosts(request);
        }
        
        public BlogControl.ApiService.Post[] GetPosts() {
            BlogControl.ApiService.GetPostsRequest inValue = new BlogControl.ApiService.GetPostsRequest();
            inValue.Body = new BlogControl.ApiService.GetPostsRequestBody();
            BlogControl.ApiService.GetPostsResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).GetPosts(inValue);
            return retVal.Body.GetPostsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetPostsResponse> BlogControl.ApiService.ApiSoap.GetPostsAsync(BlogControl.ApiService.GetPostsRequest request) {
            return base.Channel.GetPostsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.GetPostsResponse> GetPostsAsync() {
            BlogControl.ApiService.GetPostsRequest inValue = new BlogControl.ApiService.GetPostsRequest();
            inValue.Body = new BlogControl.ApiService.GetPostsRequestBody();
            return ((BlogControl.ApiService.ApiSoap)(this)).GetPostsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.GetCategoriesResponse BlogControl.ApiService.ApiSoap.GetCategories(BlogControl.ApiService.GetCategoriesRequest request) {
            return base.Channel.GetCategories(request);
        }
        
        public BlogControl.ApiService.Category[] GetCategories() {
            BlogControl.ApiService.GetCategoriesRequest inValue = new BlogControl.ApiService.GetCategoriesRequest();
            inValue.Body = new BlogControl.ApiService.GetCategoriesRequestBody();
            BlogControl.ApiService.GetCategoriesResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).GetCategories(inValue);
            return retVal.Body.GetCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetCategoriesResponse> BlogControl.ApiService.ApiSoap.GetCategoriesAsync(BlogControl.ApiService.GetCategoriesRequest request) {
            return base.Channel.GetCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.GetCategoriesResponse> GetCategoriesAsync() {
            BlogControl.ApiService.GetCategoriesRequest inValue = new BlogControl.ApiService.GetCategoriesRequest();
            inValue.Body = new BlogControl.ApiService.GetCategoriesRequestBody();
            return ((BlogControl.ApiService.ApiSoap)(this)).GetCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.GetCategoryResponse BlogControl.ApiService.ApiSoap.GetCategory(BlogControl.ApiService.GetCategoryRequest request) {
            return base.Channel.GetCategory(request);
        }
        
        public BlogControl.ApiService.Category GetCategory(int id) {
            BlogControl.ApiService.GetCategoryRequest inValue = new BlogControl.ApiService.GetCategoryRequest();
            inValue.Body = new BlogControl.ApiService.GetCategoryRequestBody();
            inValue.Body.id = id;
            BlogControl.ApiService.GetCategoryResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).GetCategory(inValue);
            return retVal.Body.GetCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.GetCategoryResponse> BlogControl.ApiService.ApiSoap.GetCategoryAsync(BlogControl.ApiService.GetCategoryRequest request) {
            return base.Channel.GetCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.GetCategoryResponse> GetCategoryAsync(int id) {
            BlogControl.ApiService.GetCategoryRequest inValue = new BlogControl.ApiService.GetCategoryRequest();
            inValue.Body = new BlogControl.ApiService.GetCategoryRequestBody();
            inValue.Body.id = id;
            return ((BlogControl.ApiService.ApiSoap)(this)).GetCategoryAsync(inValue);
        }
        
        public bool DeleteCategory(int id) {
            return base.Channel.DeleteCategory(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCategoryAsync(int id) {
            return base.Channel.DeleteCategoryAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.AddCategoryResponse BlogControl.ApiService.ApiSoap.AddCategory(BlogControl.ApiService.AddCategoryRequest request) {
            return base.Channel.AddCategory(request);
        }
        
        public bool AddCategory(BlogControl.ApiService.Category category) {
            BlogControl.ApiService.AddCategoryRequest inValue = new BlogControl.ApiService.AddCategoryRequest();
            inValue.Body = new BlogControl.ApiService.AddCategoryRequestBody();
            inValue.Body.category = category;
            BlogControl.ApiService.AddCategoryResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).AddCategory(inValue);
            return retVal.Body.AddCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.AddCategoryResponse> BlogControl.ApiService.ApiSoap.AddCategoryAsync(BlogControl.ApiService.AddCategoryRequest request) {
            return base.Channel.AddCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.AddCategoryResponse> AddCategoryAsync(BlogControl.ApiService.Category category) {
            BlogControl.ApiService.AddCategoryRequest inValue = new BlogControl.ApiService.AddCategoryRequest();
            inValue.Body = new BlogControl.ApiService.AddCategoryRequestBody();
            inValue.Body.category = category;
            return ((BlogControl.ApiService.ApiSoap)(this)).AddCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BlogControl.ApiService.UpdateCategoryResponse BlogControl.ApiService.ApiSoap.UpdateCategory(BlogControl.ApiService.UpdateCategoryRequest request) {
            return base.Channel.UpdateCategory(request);
        }
        
        public bool UpdateCategory(BlogControl.ApiService.Category category) {
            BlogControl.ApiService.UpdateCategoryRequest inValue = new BlogControl.ApiService.UpdateCategoryRequest();
            inValue.Body = new BlogControl.ApiService.UpdateCategoryRequestBody();
            inValue.Body.category = category;
            BlogControl.ApiService.UpdateCategoryResponse retVal = ((BlogControl.ApiService.ApiSoap)(this)).UpdateCategory(inValue);
            return retVal.Body.UpdateCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BlogControl.ApiService.UpdateCategoryResponse> BlogControl.ApiService.ApiSoap.UpdateCategoryAsync(BlogControl.ApiService.UpdateCategoryRequest request) {
            return base.Channel.UpdateCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<BlogControl.ApiService.UpdateCategoryResponse> UpdateCategoryAsync(BlogControl.ApiService.Category category) {
            BlogControl.ApiService.UpdateCategoryRequest inValue = new BlogControl.ApiService.UpdateCategoryRequest();
            inValue.Body = new BlogControl.ApiService.UpdateCategoryRequestBody();
            inValue.Body.category = category;
            return ((BlogControl.ApiService.ApiSoap)(this)).UpdateCategoryAsync(inValue);
        }
    }
}
