//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknoBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int ID { get; set; }
        public string AuthorID { get; set; }
        public string Caption { get; set; }
        public string Data { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
